name: permut
version: "2.0.6"
license: "GPL-2.0-or-later"
date: 2026-07-31
description: |
    A package to deal with permutability in finite groups

authors:
    - name: Adolfo Ballester-Bolinches
      url: mailto:Adolfo.Ballester@uv.es
    - name: Enric Cosme-Llópez
      url: https://www.uv.es/coslloen
    - name: Ramón Esteban-Romero
      url: https://www.uv.es/estebanr

maintainers:
    - name: Ramón Esteban-Romero
      url: https://www.uv.es/estebanr

GAP: "4.11"

needed-pkgs:
    - name: "format"
      version: "1.3"
      url: "https://gap-packages.github.io/format/"

www: https://gap-packages.github.io/permut/
readme: README.md
packageinfo: https://gap-packages.github.io/permut/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/permut/releases/download/v2.0.6/permut-2.0.6.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/permut/releases/download/v2.0.6/permut-2.0.6.tar.bz2
    - name: .zip
      url: https://github.com/gap-packages/permut/releases/download/v2.0.6/permut-2.0.6.zip

abstract: |
    This package provides functions for computing with permutability in finite groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    permutability, PT-group, PST-group, T-group, mutually permutable, totally permutable, Dedekind group, Iwasawa group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BCE26</span>]   <b class='BibAuthor'>Ballester-Bolinches, A., Cosme-Llópez, E. and Esteban-Romero, R.</b>,
     <i class='BibTitle'>permut, A package to deal with permutability in finite groups,
             Version 2.0.6</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/permut/">https://gap-packages.github.io/permut/</a></span>.
    </p>
    

bibtex: |
    @misc{ permut,
      author =           {Ballester\texttt{\symbol{45}}Bolinches,     A.     and
                          Cosme\texttt{\symbol{45}}Ll{\a'o}pez,      E.      and
                          Esteban\texttt{\symbol{45}}Romero, R.},
      title =            {{permut},  {A  package  to  deal with permutability in
                          finite groups}, {V}ersion 2.0.6},
      month =            {Jul},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/permut/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{permut/}}},
      keywords =         {permutability;            PT\texttt{\symbol{45}}group;
                          PST\texttt{\symbol{45}}group;
                          T\texttt{\symbol{45}}group;    mutually    permutable;
                          totally permutable; Dedekind group; Iwasawa group},
      printedkey =       {BCE26}
    }

