name: permut
version: "2.0.5"
license: "GPL-2.0-or-later"
date: 2024-01-11
description: |
    A package to deal with permutability in finite groups

authors:
    - name: Adolfo Ballester-Bolinches
      url: mailto:Adolfo.Ballester@uv.es
    - name: Enric Cosme-Ll贸pez
      url: https://www.uv.es/coslloen
    - name: Ram贸n Esteban-Romero
      url: https://www.uv.es/estebanr

maintainers:
    - name: Ram贸n Esteban-Romero
      url: https://www.uv.es/estebanr

GAP: "4.7.4"

needed-pkgs:
    - name: "format"
      version: "1.3"
      url: "https://gap-packages.github.io/format/"

www: https://gap-packages.github.io/permut/
readme: README.md
packageinfo: https://gap-packages.github.io/permut/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/permut/releases/download/v2.0.5/permut-2.0.5.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/permut/releases/download/v2.0.5/permut-2.0.5.tar.bz2
    - name: .zip
      url: https://github.com/gap-packages/permut/releases/download/v2.0.5/permut-2.0.5.zip

abstract: |
    This package provides functions for computing with permutability in finite groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    permutability, PT-group, PST-group, T-group, mutually permutable, totally permutable, Dedekind group, Iwasawa group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BCE24</span>]   <b class='BibAuthor'>Ballester-Bolinches, A., Cosme-Ll贸pez, E. and Esteban-Romero, R.</b>,
     <i class='BibTitle'>permut, A package to deal with permutability in finite groups,
             Version 2.0.5</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/permut/">https://gap-packages.github.io/permut/</a></span>.
    </p>
    

bibtex: |
    @misc{ permut2.0.5,
      author =           {Ballester-Bolinches,  A. and Cosme-Ll{\a'o}pez, E. and
                          Esteban-Romero, R.},
      title =            {{permut},  A  package  to  deal  with permutability in
                          finite groups, {V}ersion 2.0.5},
      month =            {Jan},
      year =             {2024},
      note =             {Refereed GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/permut/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{permut/}}},
      keywords =         {permutability;  PT-group; PST-group; T-group; mutually
                          permutable;   totally   permutable;   Dedekind  group;
                          Iwasawa group},
      printedkey =       {BCE24}
    }

